apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: custom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: custom_db
        ports:
        - containerPort: 3306
